accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login, name="login"),
    path('register', views.register, name="register"),
    path('logout', views.logout, name="logout"),
    path('dashboard', views.dashboard, name="dashboard"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('cars_list/', include('cars.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact/', include('contacts.urls')),
    path('blog/', include('blog.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post, name="blog"),
    path('blog', views.blog, name="post"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from contacts.models import Contacts
from cars.models import CarsList

# from django.shortcuts import render, redirect
# from django.contrib import messages, auth
# from django.contrib.auth.models import User


def register(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, "Username alrady taken.")
                return redirect('accounts:register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, "Email alrady taken.")
                    return redirect('accounts:register')
                else:
                    user = User.objects.create_user(
                        username=username, email=email, password=password, first_name=first_name, last_name=last_name,)
                    user.save()
                    messages.success(request, "You are registred. Log in")
                    return redirect('accounts:login')
        else:
            messages.error(request, "Passwords do not match")
        return redirect('accounts:register')
    else:
        return render(request, "accounts/register.html")


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, "You are logged in")
            logged_in = True
            return redirect('accounts:dashboard')
        else:
            messages.error(request, "Login or password incorrect")
            return redirect('accounts:login')
    else:
        return render(request, "accounts/login.html")


def logout(request):
    if request.method == "POST":
        auth.logout(request)
    messages.success(request, "See you later!")
    return redirect("index")


def dashboard(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        orders = Contacts.objects.all().filter(user_id=user_id)

        listed_cars = CarsList.objects.all()
        context = {
            'orders': orders,
            'listed_cars': listed_cars
        }

    return render(request, "accounts/dashboard.html", context)

templates/accounts/dashboard.html
{% extends 'base.html' %} {% block title %}DashBoard{% endblock %} {% load static %} {% block content %} {% include "parts/_navbar.html" %}

<style type="text/css">
    .site-navbar {
        background: lightslategray;
        -webkit-box-shadow: 0px 13px 25px 0px rgba(0, 0, 0, 0.75);
        -moz-box-shadow: 0px 13px 25px 0px rgba(0, 0, 0, 0.75);
        box-shadow: 0px 13px 25px 0px rgba(0, 0, 0, 0.75);
        position: fixed;
        height: 100px;
    }
</style>

<div class="container-fluid dash">
    <div class="container">
        <div class="row">

            <div class="header__burger active">
                <span class='spin'></span>
                <div class="header__menu active">
                    <ul class="header__menu__ul">DASHBOARD<span class="UserName">{{ user.first_name }} {{ user.last_name }}`S
              <span style="color:white;text-transform:lowercase">have <span
                  class="badge badge-primary badge-pill">{{ orders.count }}</span> orders:</span>
                        </span>
                        {% for order in orders %}
                        <button type="button" class="btn btn-link dash_modal" data-toggle="modal" data-target="#exampleModal" data-car_id={{order.car_id}} data-whatever={{order.car}}>{{order.car}}
            <small>{{ order.contact_date }}</small>
            <span class='single_car'>{% for car in listed_cars %}{% if car.id == order.car_id %}<img class="d-block w-100"
                  src="{{ car.photo_main.url }}" alt="First slide">{% endif %}{% endfor %}</span></button> {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-12 right_side_bar">
            <h1>WELLCOME <span class="UserName"><span style='text-decoration:underline'>{{ user.first_name }} {{ user.last_name }}</span></span>
            </h1>
            <div class='col-6 offset-6'>
                <ul class='dash_ul'>
                    <li class='disabled'>Registration date: <span style='text-decoration:underline'>{{ user.date_joined }}</span></li>
                    <li><span class="UserName"><span style='text-decoration:underline'>{{ user.first_name }} {{ user.last_name }}</span></span>
                    </li>
                    <li>e-mail: <span style='text-decoration:underline'>{{ user.email }}</span> </li>
                    <li>{{ user.name }}</li>
                    <li>Last login: <span style='text-decoration:underline'>{{ user.last_login }}</span></li>
                </ul>
            </div>

            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Leave coment for: </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
                        </div>
                        <div class="modal-body">
                            <form action="{% url 'blog:post' %}" method='POST'>
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Recipient:</label>
                                    <input type="text" class="form-control car_name" name='car_name' id="recipient-name">
                                    <input type='hidden' name='car_id' id='car_id' />
                                    <input type='hidden' name='author_id' value={{user.first_name}}&nbsp;{{user.last_name}}>
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Message:</label>
                                    <textarea class="form-control" name="text_area" id="message-text"></textarea>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Send message</button>
                                </div>
                            </form>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
    body {
        color: #fff;
        background: #63738a;
        font-family: 'Roboto', sans-serif;
    }

    .form-control {
        height: 40px;
        box-shadow: none;
        color: #969fa4;
    }

    .form-control:focus {
        border-color: #5cb85c;
    }

    .form-control,
    .btn {
        border-radius: 3px;
    }

    .signup-form {
        width: 400px;
        margin: 0 auto;
        padding: 30px 0;
    }

    .signup-form h2 {
        color: #636363;
        margin: 0 0 15px;
        position: relative;
        text-align: center;
    }

    .signup-form h2:before,
    .signup-form h2:after {
        content: "";
        height: 2px;
        width: 30%;
        background: #d4d4d4;
        position: absolute;
        top: 50%;
        z-index: 2;
    }

    .signup-form h2:before {
        left: 0;
    }

    .signup-form h2:after {
        right: 0;
    }

    .signup-form .hint-text {
        color: #999;
        margin-bottom: 30px;
        text-align: center;
    }

    .signup-form form {
        color: #999;
        border-radius: 3px;
        margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }

    .signup-form .form-group {
        margin-bottom: 20px;
    }

    .signup-form input[type="checkbox"] {
        margin-top: 3px;
    }

    .signup-form .btn {
        font-size: 16px;
        font-weight: bold;
        min-width: 140px;
        outline: none !important;
    }

    .signup-form .row div:first-child {
        padding-right: 10px;
    }

    .signup-form .row div:last-child {
        padding-left: 10px;
    }

    .signup-form a {
        color: #fff;
        text-decoration: underline;
    }

    .signup-form a:hover {
        text-decoration: none;
    }

    .signup-form form a {
        color: #5cb85c;
        text-decoration: none;
    }

    .signup-form form a:hover {
        text-decoration: underline;
    }
</style>
<div class='container'>
    <div class="signup-form reg">
        <form action="{% url 'accounts:login' %}" class='foarm' method="POST">
            {% csrf_token %}
            <h2>Login</h2>
            {% include 'parts/_alerts.html' %}
            <div class="form-group">
                <div class="row">
                    <input type="text" class="form-control" name="username" placeholder="Username" required="required">
                    <input type="password" class="form-control" name="password" placeholder="Password"
                        required="required">
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-lg btn-block">Login</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %} {% block title %} | Register {% endblock %} {% load
static %} {% include "partials/_header_internal.html" %} {% block content %}
<style type="text/css">
  body {
    color: #fff;
    background: #63738a;
    font-family: "Roboto", sans-serif;
  }

  .form-control {
    height: 40px;
    box-shadow: none;
    color: #969fa4;
  }

  .form-control:focus {
    border-color: #5cb85c;
  }

  .form-control,
  .btn {
    border-radius: 3px;
  }

  .signup-form {
    width: 400px;
    margin: 0 auto;
    padding: 30px 0;
  }

  .signup-form h2 {
    color: #636363;
    margin: 0 0 15px;
    position: relative;
    text-align: center;
  }

  .signup-form h2:before,
  .signup-form h2:after {
    content: "";
    height: 2px;
    width: 30%;
    background: #d4d4d4;
    position: absolute;
    top: 50%;
    z-index: 2;
  }

  .signup-form h2:before {
    left: 0;
  }

  .signup-form h2:after {
    right: 0;
  }

  .signup-form .hint-text {
    color: #999;
    margin-bottom: 30px;
    text-align: center;
  }

  .signup-form form {
    color: #999;
    border-radius: 3px;
    margin-bottom: 15px;
    background: #f2f3f7;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    padding: 30px;
  }

  .signup-form .form-group {
    margin-bottom: 20px;
  }

  .signup-form input[type="checkbox"] {
    margin-top: 3px;
  }

  .signup-form .btn {
    font-size: 16px;
    font-weight: bold;
    min-width: 140px;
    outline: none !important;
  }

  .signup-form .row div:first-child {
    padding-right: 10px;
  }

  .signup-form .row div:last-child {
    padding-left: 10px;
  }

  .signup-form a {
    color: #fff;
    text-decoration: underline;
  }

  .signup-form a:hover {
    text-decoration: none;
  }

  .signup-form form a {
    color: #5cb85c;
    text-decoration: none;
  }

  .signup-form form a:hover {
    text-decoration: underline;
  }
</style>

<div class="signup-form reg">
  <form action="{% url 'accounts:register' %}" class="foarm" method="POST">
    {% csrf_token %}
    <h2>Register</h2>
    {% include 'parts/_alerts.html' %}
    <div class="form-group">
      <div class="row">
        <div class="col-6">
          <input
            type="text"
            class="form-control"
            name="first_name"
            placeholder="First Name"
            required="required"
          />
        </div>

        <div class="col-6">
          <input
            type="text"
            class="form-control"
            name="last_name"
            placeholder="Last Name"
            required="required"
          />
        </div>
      </div>
    </div>
    <div class="form-group">
      <input
        type="text"
        class="form-control"
        name="username"
        placeholder="Username"
        required="required"
      />
    </div>
    <div class="form-group">
      <input
        type="email"
        class="form-control"
        name="email"
        placeholder="E-mail"
        required="required"
      />
    </div>
    <div class="form-group">
      <input
        type="password"
        class="form-control"
        name="password"
        placeholder="Password"
        required="required"
      />
    </div>
    <div class="form-group">
      <input
        type="password"
        class="form-control"
        name="confirm_password"
        placeholder="Confirm Password"
        required="required"
      />
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-success btn-lg btn-block">
        Register Now
      </button>
    </div>
  </form>
  <div class="text-center">
    Already have an account?<button
      type="button"
      class="btn btn-link"
      id="login"
      data-toggle="modal"
      data-target="#exampleModalCenter"
    >
      Sign in
    </button>
  </div>
</div>

{% endblock content %}