app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('cars_list/', include('cars.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact/', include('contacts.urls')),
    path('blog/', include('blog.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.cars, name="cars_list"),
    path('<int:cars_list_id>/', views.singlecar, name="single_car")
]

cars/models.py
from django.db import models
from carmanager.models import CarManager


class CarsList(models.Model):
    carmanager = models.ForeignKey(CarManager, on_delete=models.DO_NOTHING)
    vendor = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    engine = models.CharField(max_length=20)
    fuel_count = models.DecimalField(max_digits=3, decimal_places=1)
    color = models.CharField(max_length=20)
    doors = models.IntegerField()
    seatss = models.IntegerField()
    minimum_age = models.IntegerField()
    price = models.IntegerField()
    transmission = models.CharField(max_length=20)
    rating = models.IntegerField()
    is_published = models.BooleanField(default=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.vendor

cars/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from .models import CarsList
from .models import CarManager
# Create your views here.


def cars(request):
    carlist = CarsList.objects.all().filter(is_published=True)
    manager = CarManager.objects.all()
    paginator = Paginator(carlist, 3)
    page = request.GET.get("page")
    paged_carlist = paginator.get_page(page)
    context = {
        'carlist': paged_carlist,
        'title': "Our Cars",
        'manager': manager
    }
    return render(request, 'cars/cars.html', context)


def singlecar(request, cars_list_id):
    car = get_object_or_404(CarsList, pk=cars_list_id)
    manager = get_object_or_404(CarManager, name=car.carmanager)
    context = {
        'car': car,
        'manager': manager
    }
    return render(request, 'cars/single_car.html', context)

templates/cars/cars.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay innerpage">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <h1>Our For Rent Cars</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            {% if carlist %}
            {% for car in carlist %}
            <div class="col-lg-4 col-md-6 mb-4 cards">
                <div class="item-1">
                    <a href="#"><img src="{{ car.photo_main.url }}" alt="cars_list" class="img-fluid  car_img"></a>
                    <div class="item-1-contents">
                        <div class="text-center">
                            <h3><a href="#">{{car.vendor}} | {{car.model}}</a></h3>
                            <div class="rating">
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                                <span class="icon-star text-warning"></span>
                            </div>
                            <div class="rent-price"><span>{{car.price}} <i class="fas fa-dollar-sign dollar"></i>/</span>day</div>
                        </div>
                        <ul class="specs">
                            <li>
                                <span>Doors</span>
                                <span class="spec">{{car.doors}}</span>
                            </li>
                            <li>
                                <span>Seats</span>
                                <span class="spec">{{car.seatss}}</span>
                            </li>
                            <li>
                                <span>Transmission</span>
                                <span class="spec">{{car.transmition}}</span>
                            </li>
                            <li>
                                <span>Minium age</span>
                                <span class="spec">{{car.minimum_age}} years</span>
                            </li>
                        </ul>
                        <div class="d-flex action">
                            <a href="{% url 'cars:single_car' car.id %}" class="btn btn-primary">View this car</a>
                        </div>
                    </div>
                </div>
                <div class ="item-2">Manager is: <b>{{ car.carmanager }}</b>
                {% for man in manager %}{% if man == car.carmanager %}
                <img src = "{{ man.photo.url }}"/>{% endif %}{% endfor %}</div>
                
            </div>
            {% endfor %}
            
            {% else %}
            <div>NO CARLS FOR RENT</div>
            {% endif %}
            
<div class="col-md-12">
                {% if carlist.has_other_pages %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if carlist.has_previous %}
                        <li class="page-item"><a class="page-link"
                                href="?page={{ carlist.previous_page_number }}">Previous</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        {% for i in carlist.paginator.page_range %}
                        {% if carlist.number == i %}
                        <li class="page-item active"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if carlist.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ carlist.next_page_number }}">Next</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>

<div class="container site-section mb-5">
    {% endblock %}