accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login, name="login"),
    path('register', views.register, name="register"),
    path('logout', views.logout, name="logout"),
    path('dashboard', views.dashboard, name="dashboard"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('cars_list/', include('cars.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact/', include('contacts.urls')),
    path('blog/', include('blog.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post, name="blog"),
    path('blog', views.blog, name="post"),
]

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.cars, name="cars_list"),
    path('<int:cars_list_id>/', views.singlecar, name="single_car")
]

templates/parts/_alerts.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container msg">
    <div class="alert alert-{{ message.tags }}" alert-dismissable role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>
            {% if messages.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
            {% else %}
            {% comment %} {{ message.tags|title }} {% endcomment %}
            {% endif %}
        </strong>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/parts/_footer.html
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h2 class="footer-heading mb-4">About Us</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
            </div>
            <div class="col-lg-8 ml-auto">
                <div class="row">
                    <div class="col-lg-3">
                        <h2 class="footer-heading mb-4">Quick Links</h2>
                        <ul class="list-unstyled">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Testimonials</a></li>
                            <li><a href="#">Terms of Service</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h2 class="footer-heading mb-4">Quick Links</h2>
                        <ul class="list-unstyled">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Testimonials</a></li>
                            <li><a href="#">Terms of Service</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h2 class="footer-heading mb-4">Quick Links</h2>
                        <ul class="list-unstyled">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Testimonials</a></li>
                            <li><a href="#">Terms of Service</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h2 class="footer-heading mb-4">Quick Links</h2>
                        <ul class="list-unstyled">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Testimonials</a></li>
                            <li><a href="#">Terms of Service</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
                <div class="border-top pt-5">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://www.facebook.com/profile.php?id=100007412520271" target="_blank">TYOSKA!!!</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>

        </div>
    </div>
</footer>

templates/parts/_header.html
<div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay main_header_bg">
        <div class="container">
            <div class="row align-items-center">

                <div class="col-lg-5">
                    <div class="feature-car-rent-box-1">
                        {% if rnd_car %}
                        <h3>{{rnd_car.vendor}} {{rnd_car.model}}</h3>
                        <img src="{{ rnd_car.photo_main.url }}" alt="cars_list" class="img-fluid small_car">
                        <ul class="list-unstyled">
                            <li>
                                <span>Doors</span>
                                <span class="spec">{{rnd_car.doors}}</span>
                            </li>
                            <li>
                                <span>Seats</span>
                                <span class="spec">{{rnd_car.seatss}}</span>
                            </li>
                            <li>
                                <span>Lugage</span>
                                <span class="spec">2 Suitcase/2 Bags</span>
                            </li>
                            <li>
                                <span>Transmission</span>
                                <span class="spec">{{rnd_car.transmission}}</span>
                            </li>
                            <li>
                                <span>Minium age</span>
                                <span class="spec">{{rnd_car.minimum_age}}</span>
                            </li>
                        </ul>
                        <div class="d-flex align-items-center bg-light p-3">
                            <span style="color: red;">${{rnd_car.price}}/day</span>
                            <a href="{% url 'cars:cars_list' %}" class="ml-auto btn btn-primary">Rent Now</a>
                        </div>{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/parts/_header_internal.html
  <div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 overlay innerpage">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-lg-6 text-center">
            <h1>{{title}}</h1>
            <p>{{subcribe}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>

templates/parts/_navbar.html
<div class="site-wrap" id="home-section">
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

        <header class="site-navbar site-navbar-target" role="banner">

            <div class="container">
                <div class="row align-items-center position-relative">

                    <div class="">
                        <div class="site-logo">
                            <a href="{% url 'index' %}">{{title}}</a>
                        </div>
                    </div>

                    <div class="text-right">


                        <span class="d-inline-block d-lg-none"><a href="#"
                                class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span
                                    class="icon-menu h3 text-white"></span></a></span>
                        <nav class="site-navigation text-right  d-lg-block" role="navigation">
                            <ul class="site-menu main-menu js-clone-nav ">
                                <li {% if '/' == request.path %}class="active" {% else %}{% endif %}><a
                                        href="{% url 'index' %}" class="nav-link">Home</a></li>
                                <li {% if 'services' in request.path %} class="active" {% endif %}><a
                                        href="{% url 'services' %}" class="nav-link">Services</a></li>
                                <li {% if 'cars' in request.path %} class="active" {% endif %}><a href="{% url 'cars:cars_list' %}"
                                        class="nav-link">Cars</a></li>
                                <li {% if 'about' in request.path %}class="active" {% else %}{% endif %}><a
                                        href="{% url 'about' %}" class="nav-link">About</a></li>
                                <li {% if 'blog' in request.path %}class="active" {% else %}{% endif %}><a
                                        href="{% url 'blog:blog' %}" class="nav-link">Blog</a></li>
                                <li {% if 'contactus' in request.path %}class="active" {% else %}{% endif %}><a
                                        href="{% url 'contactus' %}" class="nav-link">Contact</a></li>
                                {% if user.is_authenticated %}
                                <li {% if 'dashboard' in request.path %}class="active" {% else %}{% endif %}><a
                                    href="{% url 'accounts:dashboard' %}" class="nav-link">Hi {{user.username}}</a></li>
                                    <li class='nav-item'><a href="javascript:{document.getElementById('logout').submit()}"
                                        class="send_logout_form">Logout</a></li>
                                    <form action="{% url 'accounts:logout' %}" method="POST" id='logout'>
                                        {% csrf_token %}
                                        <input type="hidden">
                                    </form>
                                {% else %}
                                <li {% if 'register' in request.path %}class="active" {% else %}{% endif %}><a
                                    href="{% url 'accounts:register' %}" class="nav-link">Register</a></li>
                                        
                                <li {% if 'login' in request.path %}class="active" {% else %}{% endif %}><a
                                        href="{% url 'accounts:login' %}" class="nav-link">Login</a></li>
                                {% endif %}
                                {% include 'parts/_alerts.html' %}
                            </ul>
                        </nav>
                    </div>


                </div>
            </div>
            


        </header>
</div>